from pathlib import Path
from dataclasses import dataclass
from collections.abc import Sequence

from ..layout import (
    PARAMETERS_FILENAME as PARAMETERS_FILENAME,
    CHANNEL_1_BINARY_FILENAME as CHANNEL_1_BINARY_FILENAME,
    COMBINED_METADATA_FILENAME as COMBINED_METADATA_FILENAME,
    ACQUISITION_PARAMETERS_FILENAME as ACQUISITION_PARAMETERS_FILENAME,
    REGISTRATION_DATA_DIRECTORY_NAME as REGISTRATION_DATA_DIRECTORY_NAME,
    TRACKING_TEMPLATE_MASKS_FILENAME as TRACKING_TEMPLATE_MASKS_FILENAME,
    RecordingArrays as RecordingArrays,
    RegistrationArrays as RegistrationArrays,
    resolve_plane_path as resolve_plane_path,
    resolve_output_path as resolve_output_path,
    resolve_dataset_path as resolve_dataset_path,
    resolve_plane_specifier as resolve_plane_specifier,
)
from .context import (
    extract_unique_components as extract_unique_components,
    load_acquisition_parameters as load_acquisition_parameters,
)
from ..dataclasses import AcquisitionParameters as AcquisitionParameters

@dataclass(frozen=True, slots=True)
class RecordingPlanes:
    output_root: Path
    plane_count: int
    plane_paths: tuple[Path, ...] = ...
    plane_specifiers: tuple[str, ...] = ...
    registered_planes: tuple[int, ...] = ...
    processed: bool = ...
    resolved: bool = ...

@dataclass(frozen=True, slots=True)
class DatasetRecordings:
    dataset_name: str
    recording_roots: tuple[Path, ...] = ...
    recording_ids: tuple[str, ...] = ...
    dataset_paths: tuple[Path, ...] = ...
    extracted_recordings: tuple[str, ...] = ...
    discovered: bool = ...

def resolve_recording_planes(output_root: Path, data_path: Path | None = None) -> RecordingPlanes: ...
def resolve_dataset_recordings(recording_roots: Sequence[Path], dataset_name: str) -> DatasetRecordings: ...
def is_recording_processed(output_root: Path) -> bool: ...
def is_plane_registered(output_root: Path, plane_index: int) -> bool: ...
def is_plane_converted(output_root: Path, plane_index: int) -> bool: ...
def is_plane_processed(output_root: Path, plane_index: int) -> bool: ...
def is_recording_extractable(output_root: Path, dataset_name: str) -> bool: ...
def is_dataset_discovered(output_root: Path, dataset_name: str) -> bool: ...
def resolve_acquisition_parameters(output_root: Path, data_path: Path | None) -> AcquisitionParameters | None: ...
