from dataclasses import field, dataclass

from PySide6 import QtGui
from _typeshed import Incomplete

@dataclass(frozen=True, slots=True)
class _CommonStyle:
    white_label: str = ...
    icon_size: int = ...
    default_mask_opacity: int = ...
    group_box: str = ...
    edit_width: int = ...
    button_pressed: str = ...
    button_unpressed: str = ...
    menu: str = ...

@dataclass(frozen=True, slots=True)
class _PlotStyle:
    scatter_point_size: int = ...
    legend_headroom: float = ...
    legend_horizontal_spacing: int = ...
    legend_offset: tuple[int, int] = ...
    left_axis_width: int = ...
    bottom_axis_height: int = ...

@dataclass(frozen=True, slots=True)
class _FontStyle:
    plot_title_size: str = ...
    label_size: str = ...
    small: QtGui.QFont = field(default_factory=Incomplete)
    small_bold: QtGui.QFont = field(default_factory=Incomplete)
    large: QtGui.QFont = field(default_factory=Incomplete)
    large_bold: QtGui.QFont = field(default_factory=Incomplete)

@dataclass(frozen=True, slots=True)
class _ROIViewerStyle:
    colorbar_max_height: int = ...
    colorbar_sample_count: int = ...
    colorbar_row_count: int = ...
    window_geometry: tuple[int, int, int, int] = ...

@dataclass(frozen=True, slots=True)
class _TrackingViewerStyle:
    window_geometry: tuple[int, int, int, int] = ...

@dataclass(frozen=True, slots=True)
class _BinaryPlayerStyle:
    image_plot_stretch: tuple[int, int] = ...
    window_geometry: tuple[int, int, int, int] = ...
    legend_column_count: int = ...

@dataclass(frozen=True, slots=True)
class _PCViewerStyle:
    group_spacing: int = ...
    title_gutter_fraction: float = ...
    window_geometry: tuple[int, int, int, int] = ...
    legend_column_count: int = ...

@dataclass(frozen=True, slots=True)
class _Colors:
    cyan: tuple[int, int, int] = ...
    magenta: tuple[int, int, int] = ...
    red: tuple[int, int, int] = ...
    white: tuple[int, int, int] = ...
    gray: tuple[int, int, int] = ...
    silver: tuple[int, int, int] = ...
    green: tuple[int, int, int] = ...
    gold: tuple[int, int, int] = ...

COLORS: _Colors
STYLE: _CommonStyle
PLOT_STYLE: _PlotStyle
FONTS: _FontStyle
ROI_STYLE: _ROIViewerStyle
TRACKING_STYLE: _TrackingViewerStyle
BINARY_STYLE: _BinaryPlayerStyle
PC_STYLE: _PCViewerStyle
