from pathlib import Path
from dataclasses import field, dataclass

import numpy as np
from numpy.typing import NDArray as NDArray

from ..io import (
    BinaryFile as BinaryFile,
    BinaryFileCombined as BinaryFileCombined,
)
from ..dataclasses import (
    IOData as IOData,
    ROIMask as ROIMask,
    CombinedData as CombinedData,
    DetectionData as DetectionData,
    ROIStatistics as ROIStatistics,
    ExtractionData as ExtractionData,
    RuntimeContext as RuntimeContext,
    RegistrationData as RegistrationData,
    MultiRecordingRuntimeData as MultiRecordingRuntimeData,
    MultiRecordingTrackingData as MultiRecordingTrackingData,
    MultiRecordingRuntimeContext as MultiRecordingRuntimeContext,
    MultiRecordingRegistrationData as MultiRecordingRegistrationData,
)

EMPTY: NDArray[np.float32]

@dataclass(slots=True)
class SingleRecordingData:
    _contexts: list[RuntimeContext]
    _combined: CombinedData
    _view_index: int = ...
    _channel_1_binaries: dict[int, BinaryFile] = field(init=False)
    _channel_2_binaries: dict[int, BinaryFile] = field(init=False)
    _combined_binary: BinaryFileCombined = field(init=False)
    _combined_binary_channel_2: BinaryFileCombined | None = field(init=False)
    _view_labels: tuple[str, ...] = field(init=False)
    def __post_init__(self) -> None: ...
    @property
    def view_index(self) -> int: ...
    @property
    def plane_count(self) -> int: ...
    @property
    def view_labels(self) -> tuple[str, ...]: ...
    @property
    def frame_height(self) -> int: ...
    @property
    def frame_width(self) -> int: ...
    @property
    def frame_count(self) -> int: ...
    @property
    def sampling_rate(self) -> float: ...
    @property
    def tau(self) -> float: ...
    @property
    def roi_statistics(self) -> list[ROIStatistics]: ...
    @property
    def roi_count(self) -> int: ...
    @property
    def cell_count(self) -> int: ...
    @property
    def cell_fluorescence(self) -> NDArray[np.float32]: ...
    @property
    def cell_fluorescence_channel_2(self) -> NDArray[np.float32]: ...
    @property
    def neuropil_fluorescence(self) -> NDArray[np.float32]: ...
    @property
    def neuropil_fluorescence_channel_2(self) -> NDArray[np.float32]: ...
    @property
    def subtracted_fluorescence(self) -> NDArray[np.float32]: ...
    @property
    def subtracted_fluorescence_channel_2(self) -> NDArray[np.float32]: ...
    @property
    def spikes(self) -> NDArray[np.float32]: ...
    @property
    def spikes_channel_2(self) -> NDArray[np.float32]: ...
    @property
    def two_channels(self) -> bool: ...
    @property
    def cell_classification(self) -> NDArray[np.float32]: ...
    @property
    def cell_classification_channel_2(self) -> NDArray[np.float32]: ...
    @property
    def cell_colocalization(self) -> NDArray[np.float32]: ...
    @property
    def mean_image(self) -> NDArray[np.float32]: ...
    @property
    def enhanced_mean_image(self) -> NDArray[np.float32]: ...
    @property
    def maximum_projection(self) -> NDArray[np.float32]: ...
    @property
    def correlation_map(self) -> NDArray[np.float32]: ...
    @property
    def mean_image_channel_2(self) -> NDArray[np.float32]: ...
    @property
    def enhanced_mean_image_channel_2(self) -> NDArray[np.float32]: ...
    @property
    def correlation_map_channel_2(self) -> NDArray[np.float32]: ...
    @property
    def maximum_projection_channel_2(self) -> NDArray[np.float32]: ...
    @property
    def corrected_structural_mean_image(self) -> NDArray[np.float32]: ...
    @property
    def roi_diameter(self) -> int: ...
    @property
    def aspect_ratio(self) -> float: ...
    @property
    def rigid_y_offsets(self) -> NDArray[np.int32]: ...
    @property
    def rigid_x_offsets(self) -> NDArray[np.int32]: ...
    @property
    def principal_component_extreme_images(self) -> NDArray[np.float32] | None: ...
    @property
    def principal_component_shift_metrics(self) -> NDArray[np.float32] | None: ...
    @property
    def principal_component_projections(self) -> NDArray[np.float32] | None: ...
    @property
    def principal_component_count(self) -> int: ...
    @property
    def recording_label(self) -> str: ...
    @property
    def output_path(self) -> Path: ...
    @property
    def combined_binary(self) -> BinaryFileCombined: ...
    def read_stitched_frame(self, frame_index: int) -> NDArray[np.int16]: ...
    def read_stitched_frame_channel_2(self, frame_index: int) -> NDArray[np.int16]: ...
    def plane_rigid_offsets(self, plane_index: int) -> tuple[NDArray[np.int32], NDArray[np.int32]]: ...
    def switch_view(self, view_index: int) -> None: ...
    @classmethod
    def from_data(cls, root_path: Path, view_index: int = -1) -> SingleRecordingData: ...
    @property
    def _current_plane_index(self) -> int: ...
    @property
    def _current_extraction(self) -> ExtractionData: ...
    @property
    def _current_io(self) -> IOData: ...
    @property
    def _current_registration(self) -> RegistrationData: ...
    @property
    def _current_detection(self) -> DetectionData: ...

@dataclass(slots=True)
class MultiRecordingData:
    _context: MultiRecordingRuntimeContext = field(repr=False)
    def __post_init__(self) -> None: ...
    @property
    def recording_id(self) -> str: ...
    @property
    def runtime_dataset_name(self) -> str: ...
    @property
    def data_path(self) -> Path: ...
    @property
    def has_channel_2(self) -> bool: ...
    @property
    def mean_image(self) -> NDArray[np.float32]: ...
    @property
    def enhanced_mean_image(self) -> NDArray[np.float32]: ...
    @property
    def maximum_projection(self) -> NDArray[np.float32]: ...
    @property
    def correlation_map(self) -> NDArray[np.float32]: ...
    @property
    def mean_image_channel_2(self) -> NDArray[np.float32]: ...
    @property
    def enhanced_mean_image_channel_2(self) -> NDArray[np.float32]: ...
    @property
    def maximum_projection_channel_2(self) -> NDArray[np.float32]: ...
    @property
    def correlation_map_channel_2(self) -> NDArray[np.float32]: ...
    @property
    def transformed_mean_image(self) -> NDArray[np.float32]: ...
    @property
    def transformed_enhanced_mean_image(self) -> NDArray[np.float32]: ...
    @property
    def transformed_maximum_projection(self) -> NDArray[np.float32]: ...
    @property
    def transformed_mean_image_channel_2(self) -> NDArray[np.float32]: ...
    @property
    def transformed_enhanced_mean_image_channel_2(self) -> NDArray[np.float32]: ...
    @property
    def transformed_maximum_projection_channel_2(self) -> NDArray[np.float32]: ...
    @property
    def original_masks(self) -> list[ROIStatistics]: ...
    @property
    def original_masks_channel_2(self) -> list[ROIStatistics]: ...
    @property
    def deformed_masks(self) -> list[ROIMask]: ...
    @property
    def deformed_masks_channel_2(self) -> list[ROIMask]: ...
    @property
    def template_masks(self) -> list[ROIMask]: ...
    @property
    def template_masks_channel_2(self) -> list[ROIMask]: ...
    @property
    def tracked_masks(self) -> list[ROIStatistics]: ...
    @property
    def tracked_masks_channel_2(self) -> list[ROIStatistics]: ...
    @property
    def cell_fluorescence(self) -> NDArray[np.float32]: ...
    @property
    def neuropil_fluorescence(self) -> NDArray[np.float32]: ...
    @property
    def subtracted_fluorescence(self) -> NDArray[np.float32]: ...
    @property
    def spikes(self) -> NDArray[np.float32]: ...
    @property
    def cell_fluorescence_channel_2(self) -> NDArray[np.float32]: ...
    @property
    def neuropil_fluorescence_channel_2(self) -> NDArray[np.float32]: ...
    @property
    def subtracted_fluorescence_channel_2(self) -> NDArray[np.float32]: ...
    @property
    def spikes_channel_2(self) -> NDArray[np.float32]: ...
    @property
    def cell_colocalization(self) -> NDArray[np.float32]: ...
    @property
    def _runtime(self) -> MultiRecordingRuntimeData: ...
    @property
    def _registration(self) -> MultiRecordingRegistrationData: ...
    @property
    def _tracking(self) -> MultiRecordingTrackingData: ...
    @property
    def _combined(self) -> CombinedData: ...
    @property
    def _detection(self) -> DetectionData: ...

@dataclass(slots=True)
class ViewerData:
    single_recording: SingleRecordingData
    _recordings: list[MultiRecordingData] = field(default_factory=list)
    _available_datasets: tuple[str, ...] = ...
    _active_dataset_name: str = ...
    _current_recording_index: int = ...
    _loaded_dataset_name: str = ...
    dataset_name: str = ...
    @property
    def is_multi_recording(self) -> bool: ...
    @property
    def available_datasets(self) -> tuple[str, ...]: ...
    @property
    def active_dataset_name(self) -> str: ...
    @property
    def recording_count(self) -> int: ...
    @property
    def recording_ids(self) -> tuple[str, ...]: ...
    @property
    def current_recording_index(self) -> int: ...
    @property
    def current_recording_id(self) -> str: ...
    @property
    def current_recording(self) -> MultiRecordingData: ...
    def recording(self, index: int) -> MultiRecordingData: ...
    def load_dataset(self, dataset_name: str) -> None: ...
    def unload_dataset(self) -> None: ...
    def switch_recording(self, recording_index: int) -> None: ...
    @classmethod
    def from_data(cls, root_path: Path, *, dataset: str | None = None) -> ViewerData: ...
    @staticmethod
    def _discover_dataset_names(root_path: Path) -> tuple[str, ...]: ...
    def _load_dataset_from_root(self, dataset_name: str, search_root: Path) -> None: ...
