"""Provides the orchestration layer: the pipeline job model and its prerequisite graph, the measured CPU worker and
resource-class allocation, the local batch execution engine, and the pipeline entry points.
"""

from .jobs import (
    MULTI_RECORDING_PHASES,
    SINGLE_RECORDING_PHASES,
    PipelinePhase,
    PrerequisiteScope,
    MultiRecordingJobNames,
    SingleRecordingJobNames,
    resolve_pipeline_jobs,
    order_phases_by_execution,
    resolve_downstream_phases,
    validate_job_prerequisites,
    resolve_multi_recording_jobs,
    resolve_single_recording_jobs,
    resolve_multi_recording_prerequisites,
    resolve_single_recording_prerequisites,
)
from .openmp import OpenMpStatus, resolve_openmp_runtime
from ..layout import (
    PLANE_SPECIFIER_PREFIX,
    MULTI_RECORDING_TRACKER_FILENAME,
    SINGLE_RECORDING_TRACKER_FILENAME,
    parse_plane_specifier,
    resolve_plane_specifier,
)
from .pipeline import (
    execute_multi_recording_job,
    execute_single_recording_job,
    run_multi_recording_pipeline,
    run_single_recording_pipeline,
)
from .execution import (
    PendingJob,
    JobExecutionState,
    get_execution_state,
    set_execution_state,
    resolve_session_load,
    start_execution_session,
    cancel_execution_session,
)
from .allocation import (
    ALL_CORES_REQUEST,
    DISCOVERY_WORKERS,
    EXTRACTION_WORKERS,
    PROCESSING_WORKERS,
    BINARIZATION_WORKERS,
    REGISTRATION_WORKERS,
    RESOURCE_CLASS_BY_JOB_NAME,
    ResourceClass,
    resolve_stage_workers,
)

__all__ = [
    "ALL_CORES_REQUEST",
    "BINARIZATION_WORKERS",
    "DISCOVERY_WORKERS",
    "EXTRACTION_WORKERS",
    "MULTI_RECORDING_PHASES",
    "MULTI_RECORDING_TRACKER_FILENAME",
    "PLANE_SPECIFIER_PREFIX",
    "PROCESSING_WORKERS",
    "REGISTRATION_WORKERS",
    "RESOURCE_CLASS_BY_JOB_NAME",
    "SINGLE_RECORDING_PHASES",
    "SINGLE_RECORDING_TRACKER_FILENAME",
    "JobExecutionState",
    "MultiRecordingJobNames",
    "OpenMpStatus",
    "PendingJob",
    "PipelinePhase",
    "PrerequisiteScope",
    "ResourceClass",
    "SingleRecordingJobNames",
    "cancel_execution_session",
    "execute_multi_recording_job",
    "execute_single_recording_job",
    "get_execution_state",
    "order_phases_by_execution",
    "parse_plane_specifier",
    "resolve_downstream_phases",
    "resolve_multi_recording_jobs",
    "resolve_multi_recording_prerequisites",
    "resolve_openmp_runtime",
    "resolve_pipeline_jobs",
    "resolve_plane_specifier",
    "resolve_session_load",
    "resolve_single_recording_jobs",
    "resolve_single_recording_prerequisites",
    "resolve_stage_workers",
    "run_multi_recording_pipeline",
    "run_single_recording_pipeline",
    "set_execution_state",
    "start_execution_session",
    "validate_job_prerequisites",
]
