"""Provides configuration and runtime data classes for the single-day and multi-day cindra pipelines."""

from .version import version, python_version
from .multi_day_data import (
    MultiDayIOData,
    MultiDayTimingData,
    MultiDayRuntimeData,
    MultiDayTrackingData,
    MultiDayRegistrationData,
)
from .single_day_data import (
    IOData,
    ROIMask,
    TimingData,
    CombinedData,
    DetectionData,
    ROIStatistics,
    ExtractionData,
    RegistrationData,
    SingleDayRuntimeData,
)
from .runtime_contexts import RuntimeContext, MultiDayRuntimeContext
from .multi_day_configuration import ReferenceImageType, MultiDayConfiguration
from .single_day_configuration import (
    Main,
    FileIO,
    PipelineType,
    ROIDetection,
    Registration,
    BaselineMethod,
    RuntimeSettings,
    SignalExtraction,
    SpikeDeconvolution,
    NonrigidRegistration,
    AcquisitionParameters,
    OnePhotonRegistration,
    SingleDayConfiguration,
    detect_pipeline_type,
)

__all__ = [
    "AcquisitionParameters",
    "BaselineMethod",
    "CombinedData",
    "DetectionData",
    "ExtractionData",
    "FileIO",
    "IOData",
    "Main",
    "MultiDayConfiguration",
    "MultiDayIOData",
    "MultiDayRegistrationData",
    "MultiDayRuntimeContext",
    "MultiDayRuntimeData",
    "MultiDayTimingData",
    "MultiDayTrackingData",
    "NonrigidRegistration",
    "OnePhotonRegistration",
    "PipelineType",
    "ROIDetection",
    "ROIMask",
    "ROIStatistics",
    "ReferenceImageType",
    "Registration",
    "RegistrationData",
    "RuntimeContext",
    "RuntimeSettings",
    "SignalExtraction",
    "SingleDayConfiguration",
    "SingleDayRuntimeData",
    "SpikeDeconvolution",
    "TimingData",
    "detect_pipeline_type",
    "python_version",
    "version",
]
