"""Provides configuration and runtime data classes for the single-recording and multi-recording cindra pipelines."""

from .version import version, python_version
from .runtime_contexts import RuntimeContext, MultiRecordingRuntimeContext
from .multi_recording_data import (
    MultiRecordingIOData,
    MultiRecordingTimingData,
    MultiRecordingRuntimeData,
    MultiRecordingTrackingData,
    MultiRecordingRegistrationData,
)
from .single_recording_data import (
    IOData,
    ROIMask,
    TimingData,
    CombinedData,
    DetectionData,
    ROIStatistics,
    ExtractionData,
    RegistrationData,
    SingleRecordingRuntimeData,
)
from .multi_recording_configuration import ReferenceImageType, MultiRecordingConfiguration
from .single_recording_configuration import (
    Main,
    FileIO,
    PipelineType,
    ROIDetection,
    Registration,
    BaselineMethod,
    RuntimeSettings,
    SignalExtraction,
    SpikeDeconvolution,
    NonrigidRegistration,
    AcquisitionParameters,
    OnePhotonRegistration,
    SingleRecordingConfiguration,
    detect_pipeline_type,
)

__all__ = [
    "AcquisitionParameters",
    "BaselineMethod",
    "CombinedData",
    "DetectionData",
    "ExtractionData",
    "FileIO",
    "IOData",
    "Main",
    "MultiRecordingConfiguration",
    "MultiRecordingIOData",
    "MultiRecordingRegistrationData",
    "MultiRecordingRuntimeContext",
    "MultiRecordingRuntimeData",
    "MultiRecordingTimingData",
    "MultiRecordingTrackingData",
    "NonrigidRegistration",
    "OnePhotonRegistration",
    "PipelineType",
    "ROIDetection",
    "ROIMask",
    "ROIStatistics",
    "ReferenceImageType",
    "Registration",
    "RegistrationData",
    "RuntimeContext",
    "RuntimeSettings",
    "SignalExtraction",
    "SingleRecordingConfiguration",
    "SingleRecordingRuntimeData",
    "SpikeDeconvolution",
    "TimingData",
    "detect_pipeline_type",
    "python_version",
    "version",
]
