from enum import StrEnum
from pathlib import Path
from dataclasses import field, dataclass

from ataraxis_data_structures import YamlConfig

from .single_recording_configuration import (
    PipelineType as PipelineType,
    RuntimeSettings as RuntimeSettings,
    SignalExtraction as SignalExtraction,
    SpikeDeconvolution as SpikeDeconvolution,
)

class ReferenceImageType(StrEnum):
    MEAN = "mean"
    ENHANCED_MEAN = "enhanced_mean"
    MAXIMUM_PROJECTION = "maximum_projection"

@dataclass
class RecordingIO:
    recording_directories: tuple[Path, ...] = ...
    dataset_name: str = ...
    repeat_selection: bool = ...
    def __post_init__(self) -> None: ...

@dataclass
class ROISelection:
    probability_threshold: float = ...
    maximum_size: int = ...
    mroi_region_margin: int = ...
    probability_threshold_channel_2: float | None = ...
    maximum_size_channel_2: int | None = ...
    mroi_region_margin_channel_2: int | None = ...

@dataclass
class DiffeomorphicRegistration:
    image_type: ReferenceImageType | str = ...
    grid_sampling_factor: float = ...
    scale_sampling: int = ...
    speed_factor: float = ...
    repeat_registration: bool = ...

@dataclass
class ROITracking:
    threshold: float = ...
    mask_prevalence: int = ...
    pixel_prevalence: int = ...
    step_sizes: tuple[int, int] = ...
    bin_size: int = ...
    maximum_distance: int = ...
    minimum_size: int = ...

@dataclass
class MultiRecordingConfiguration(YamlConfig):
    pipeline_type: PipelineType = field(default=PipelineType.MULTI_RECORDING, init=False)
    runtime: RuntimeSettings = field(default_factory=RuntimeSettings)
    recording_io: RecordingIO = field(default_factory=RecordingIO)
    roi_selection: ROISelection = field(default_factory=ROISelection)
    diffeomorphic_registration: DiffeomorphicRegistration = field(default_factory=DiffeomorphicRegistration)
    roi_tracking: ROITracking = field(default_factory=ROITracking)
    signal_extraction: SignalExtraction = field(default_factory=SignalExtraction)
    spike_deconvolution: SpikeDeconvolution = field(default_factory=SpikeDeconvolution)
    def save(self, file_path: Path) -> None: ...
    @classmethod
    def load(cls, file_path: Path) -> MultiRecordingConfiguration: ...
