from pathlib import Path
from dataclasses import field, dataclass

import numpy as np
from numpy.typing import NDArray as NDArray
from ataraxis_data_structures import YamlConfig

from .version import (
    version as version,
    python_version as python_version,
)
from .single_recording_data import (
    ROIMask as ROIMask,
    CombinedData as CombinedData,
    ExtractionData as ExtractionData,
    is_memory_mapped as is_memory_mapped,
)

@dataclass
class MultiRecordingIOData:
    recording_id: str = ...
    data_path: Path | None = ...
    dataset_name: str = ...
    mroi_region_borders: tuple[int, ...] = ...
    dataset_output_paths: tuple[Path, ...] = ...
    selected_roi_indices: tuple[int, ...] = ...
    selected_roi_indices_channel_2: tuple[int, ...] = ...

@dataclass
class MultiRecordingRegistrationData:
    has_registration_data: bool = ...
    deform_field_y: NDArray[np.float32] | None = ...
    deform_field_x: NDArray[np.float32] | None = ...
    transformed_mean_image: NDArray[np.float32] | None = ...
    transformed_enhanced_mean_image: NDArray[np.float32] | None = ...
    transformed_maximum_projection: NDArray[np.float32] | None = ...
    transformed_mean_image_channel_2: NDArray[np.float32] | None = ...
    transformed_enhanced_mean_image_channel_2: NDArray[np.float32] | None = ...
    transformed_maximum_projection_channel_2: NDArray[np.float32] | None = ...
    deformed_roi_masks: list[ROIMask] | None = ...
    deformed_roi_masks_channel_2: list[ROIMask] | None = ...
    def is_registered(self) -> bool: ...
    def clear(self) -> None: ...
    def prepare_for_saving(self) -> None: ...
    def release_arrays(self) -> None: ...
    def save_arrays(self, output_path: Path) -> None: ...
    def load_arrays(self, output_path: Path) -> None: ...
    def memory_map_arrays(self, output_path: Path) -> None: ...

@dataclass
class MultiRecordingTimingData:
    registration_time: int = ...
    tracking_time: int = ...
    backward_transform_time: int = ...
    total_discovery_time: int = ...
    extraction_time: int = ...
    deconvolution_time: int = ...
    total_extraction_time: int = ...
    date_processed: str = ...
    python_version: str = ...
    cindra_version: str = ...

@dataclass
class MultiRecordingTrackingData:
    template_masks: list[ROIMask] | None = ...
    template_masks_channel_2: list[ROIMask] | None = ...
    template_diameter: int = ...
    template_diameter_channel_2: int = ...
    def prepare_for_saving(self) -> None: ...
    def release_arrays(self) -> None: ...
    def save_arrays(self, output_path: Path) -> None: ...
    def load_arrays(self, output_path: Path) -> None: ...
    def memory_map_arrays(self, output_path: Path) -> None: ...

@dataclass
class MultiRecordingRuntimeData(YamlConfig):
    output_path: Path | None = ...
    io: MultiRecordingIOData = field(default_factory=MultiRecordingIOData)
    registration: MultiRecordingRegistrationData = field(default_factory=MultiRecordingRegistrationData)
    tracking: MultiRecordingTrackingData = field(default_factory=MultiRecordingTrackingData)
    extraction: ExtractionData = field(default_factory=ExtractionData)
    timing: MultiRecordingTimingData = field(default_factory=MultiRecordingTimingData)
    combined_data: CombinedData | None = ...
    def release_arrays(self) -> None: ...
    def load_arrays(self) -> None: ...
    def memory_map_arrays(self) -> None: ...
    def save(self, output_path: Path) -> None: ...
    @classmethod
    def load(cls, output_path: Path) -> MultiRecordingRuntimeData: ...
