from enum import StrEnum
from pathlib import Path
from dataclasses import field, dataclass

from ataraxis_data_structures import YamlConfig

class PipelineType(StrEnum):
    SINGLE_RECORDING = "single-recording"
    MULTI_RECORDING = "multi-recording"

class BaselineMethod(StrEnum):
    MAXIMIN = "maximin"
    CONSTANT = "constant"
    CONSTANT_PERCENTILE = "constant_percentile"

def detect_pipeline_type(file_path: Path) -> PipelineType: ...

@dataclass
class _PipelineHeader(YamlConfig):
    pipeline_type: str | None = ...

@dataclass
class RuntimeSettings:
    parallel_workers: int = ...
    display_progress_bars: bool = ...

@dataclass
class AcquisitionParameters(YamlConfig):
    frame_rate: float
    plane_number: int = ...
    channel_number: int = ...
    roi_number: int = ...
    roi_lines: tuple[tuple[int, ...], ...] = ...
    roi_x_coordinates: tuple[int, ...] = ...
    roi_y_coordinates: tuple[int, ...] = ...
    @property
    def is_mroi(self) -> bool: ...
    @property
    def virtual_plane_count(self) -> int: ...

@dataclass
class Main:
    two_channels: bool = ...
    first_channel_functional: bool = ...
    second_channel_functional: bool = ...
    tau: float = ...
    ignored_flyback_planes: tuple[int, ...] = ...
    custom_classifier_path: Path | None = ...

@dataclass
class FileIO:
    data_path: Path | None = ...
    output_path: Path | None = ...
    ignored_file_names: tuple[str, ...] = ...
    repeat_binarization: bool = ...

@dataclass
class Registration:
    repeat_registration: bool = ...
    align_by_first_channel: bool = ...
    reference_frame_count: int = ...
    batch_size: int = ...
    maximum_offset_fraction: float = ...
    spatial_smoothing_sigma: float = ...
    temporal_smoothing_sigma: float = ...
    two_step_registration: bool = ...
    bad_frame_threshold: float = ...
    normalize_frames: bool = ...
    registration_metric_principal_components: int = ...
    compute_bidirectional_phase_offset: bool = ...
    bidirectional_phase_offset_override: int = ...

@dataclass
class OnePhotonRegistration:
    enabled: bool = ...
    spatial_highpass_window: int = ...
    pre_smoothing_sigma: float = ...
    edge_taper_pixels: float = ...

@dataclass
class NonrigidRegistration:
    enabled: bool = ...
    block_size: tuple[int, int] = ...
    signal_to_noise_threshold: float = ...
    maximum_block_offset: float = ...

@dataclass
class ROIDetection:
    enabled: bool = ...
    preclassification_threshold: float = ...
    threshold_scaling: float = ...
    spatial_highpass_window: int = ...
    maximum_overlap: float = ...
    temporal_highpass_window: int = ...
    maximum_iterations: int = ...
    maximum_binned_frames: int = ...
    denoise: bool = ...
    crop_to_soma: bool = ...

@dataclass
class SignalExtraction:
    extract_neuropil: bool = ...
    allow_overlap: bool = ...
    minimum_neuropil_pixels: int = ...
    inner_neuropil_border_radius: int = ...
    cell_probability_percentile: int = ...
    classification_threshold: float = ...
    batch_size: int = ...
    colocalization_threshold: float = ...

@dataclass
class SpikeDeconvolution:
    extract_spikes: bool = ...
    neuropil_coefficient: float = ...
    baseline_method: BaselineMethod | str = ...
    baseline_window: float = ...
    baseline_sigma: float = ...
    baseline_percentile: float = ...

@dataclass
class SingleRecordingConfiguration(YamlConfig):
    pipeline_type: PipelineType = field(default=PipelineType.SINGLE_RECORDING, init=False)
    runtime: RuntimeSettings = field(default_factory=RuntimeSettings)
    main: Main = field(default_factory=Main)
    file_io: FileIO = field(default_factory=FileIO)
    registration: Registration = field(default_factory=Registration)
    one_photon_registration: OnePhotonRegistration = field(default_factory=OnePhotonRegistration)
    nonrigid_registration: NonrigidRegistration = field(default_factory=NonrigidRegistration)
    roi_detection: ROIDetection = field(default_factory=ROIDetection)
    signal_extraction: SignalExtraction = field(default_factory=SignalExtraction)
    spike_deconvolution: SpikeDeconvolution = field(default_factory=SpikeDeconvolution)
    def save(self, file_path: Path) -> None: ...
    @classmethod
    def load(cls, file_path: Path) -> SingleRecordingConfiguration: ...
