from pathlib import Path
from functools import cached_property as cached_property
from dataclasses import field, dataclass

import numpy as np
from _typeshed import Incomplete
from numpy.typing import NDArray as NDArray
from numpy.lib.npyio import NpzFile
from ataraxis_data_structures import YamlConfig

from .version import (
    version as version,
    python_version as python_version,
)

def is_memory_mapped(array: NDArray[np.generic] | None) -> bool: ...

@dataclass
class IOData:
    frame_height: int = ...
    frame_width: int = ...
    frame_count: int = ...
    sampling_rate: float = ...
    registered_binary_path: Path | None = ...
    registered_binary_path_channel_2: Path | None = ...
    output_path: Path | None = ...
    mroi_y_offset: int | None = ...
    mroi_x_offset: int | None = ...
    mroi_lines: tuple[int, ...] = ...
    plane_index: int | None = ...

@dataclass
class RegistrationData:
    valid_y_range: tuple[int, int] = ...
    valid_x_range: tuple[int, int] = ...
    bad_frames: NDArray[np.bool_] | None = ...
    bidirectional_phase_offset: int = ...
    bidirectional_phase_corrected: bool = ...
    normalization_minimum: int = ...
    normalization_maximum: int = ...
    reference_image: NDArray[np.float32] | None = ...
    rigid_y_offsets: NDArray[np.int32] | None = ...
    rigid_x_offsets: NDArray[np.int32] | None = ...
    rigid_correlations: NDArray[np.float32] | None = ...
    nonrigid_y_offsets: NDArray[np.float32] | None = ...
    nonrigid_x_offsets: NDArray[np.float32] | None = ...
    nonrigid_correlations: NDArray[np.float32] | None = ...
    principal_component_extreme_images: NDArray[np.float32] | None = ...
    principal_component_projections: NDArray[np.float32] | None = ...
    principal_component_shift_metrics: NDArray[np.float32] | None = ...
    def is_registered(self, output_path: Path | None = None) -> bool: ...
    def clear(self) -> None: ...
    def prepare_for_saving(self) -> None: ...
    def release_arrays(self) -> None: ...
    def save_arrays(self, output_path: Path) -> None: ...
    def load_arrays(self, output_path: Path) -> None: ...
    def memory_map_arrays(self, output_path: Path) -> None: ...

@dataclass
class DetectionData:
    roi_diameter: int = ...
    aspect_ratio: float = ...
    mean_image: NDArray[np.float32] | None = ...
    enhanced_mean_image: NDArray[np.float32] | None = ...
    maximum_projection: NDArray[np.float32] | None = ...
    correlation_map: NDArray[np.float32] | None = ...
    roi_diameter_channel_2: int = ...
    mean_image_channel_2: NDArray[np.float32] | None = ...
    enhanced_mean_image_channel_2: NDArray[np.float32] | None = ...
    maximum_projection_channel_2: NDArray[np.float32] | None = ...
    correlation_map_channel_2: NDArray[np.float32] | None = ...
    def prepare_for_saving(self) -> None: ...
    def release_arrays(self) -> None: ...
    def save_arrays(self, output_path: Path) -> None: ...
    def load_arrays(self, output_path: Path) -> None: ...
    def memory_map_arrays(self, output_path: Path) -> None: ...

@dataclass
class ROIMask:
    y_pixels: NDArray[np.int32]
    x_pixels: NDArray[np.int32]
    pixel_weights: NDArray[np.float32]
    centroid: tuple[int, int]
    frame_width: int
    radius: float = ...
    cluster_id: int = ...
    recording_count: int = ...
    overlap_mask: NDArray[np.bool_] | None = ...
    @cached_property
    def raveled_pixels(self) -> NDArray[np.int32]: ...
    @cached_property
    def circle_pixels(self) -> tuple[NDArray[np.int32], NDArray[np.int32]]: ...
    @staticmethod
    def save_list(mask_list: list[ROIMask], file_path: Path) -> None: ...
    @staticmethod
    def load_list(file_path: Path) -> list[ROIMask]: ...

@dataclass
class ROIStatistics:
    mask: ROIMask
    footprint: int = ...
    compactness: float = ...
    solidity: float = ...
    pixel_count: int = ...
    soma_mask: NDArray[np.bool_] | None = ...
    aspect_ratio: float = ...
    normalized_pixel_count: float = ...
    skewness: float | None = ...
    neuropil_mask: NDArray[np.int32] | None = ...
    plane_index: int = ...
    @staticmethod
    def save_list(roi_list: list[ROIStatistics], masks_path: Path, stats_path: Path) -> None: ...
    @staticmethod
    def load_list(masks_path: Path, stats_path: Path) -> list[ROIStatistics]: ...

@dataclass
class ExtractionData:
    roi_statistics: list[ROIStatistics] | None = ...
    cell_fluorescence: NDArray[np.float32] | None = ...
    neuropil_fluorescence: NDArray[np.float32] | None = ...
    subtracted_fluorescence: NDArray[np.float32] | None = ...
    spikes: NDArray[np.float32] | None = ...
    cell_classification: NDArray[np.float32] | None = ...
    roi_statistics_channel_2: list[ROIStatistics] | None = ...
    cell_fluorescence_channel_2: NDArray[np.float32] | None = ...
    neuropil_fluorescence_channel_2: NDArray[np.float32] | None = ...
    subtracted_fluorescence_channel_2: NDArray[np.float32] | None = ...
    spikes_channel_2: NDArray[np.float32] | None = ...
    cell_classification_channel_2: NDArray[np.float32] | None = ...
    cell_colocalization: NDArray[np.float32] | None = ...
    corrected_structural_mean_image: NDArray[np.float32] | None = ...
    def prepare_for_saving(self) -> None: ...
    def release_arrays(self) -> None: ...
    def save_arrays(self, output_path: Path) -> None: ...
    def load_arrays(self, output_path: Path) -> None: ...
    def load_results(self, output_path: Path) -> None: ...
    def memory_map_arrays(self, output_path: Path) -> None: ...
    def memory_map_results(self, output_path: Path) -> None: ...

@dataclass
class TimingData:
    binarization_time: int = ...
    registration_time: int = ...
    two_step_registration_time: int = ...
    registration_metrics_time: int = ...
    detection_time: int = ...
    extraction_time: int = ...
    classification_time: int = ...
    deconvolution_time: int = ...
    detection_time_channel_2: int = ...
    extraction_time_channel_2: int = ...
    classification_time_channel_2: int = ...
    deconvolution_time_channel_2: int = ...
    total_plane_time: int = ...
    date_processed: str = ...
    python_version: str = ...
    cindra_version: str = ...

@dataclass
class SingleRecordingRuntimeData(YamlConfig):
    output_path: Path | None = ...
    io: IOData = field(default_factory=IOData)
    registration: RegistrationData = field(default_factory=RegistrationData)
    detection: DetectionData = field(default_factory=DetectionData)
    extraction: ExtractionData = field(default_factory=ExtractionData)
    timing: TimingData = field(default_factory=TimingData)
    def release_arrays(self) -> None: ...
    def load_arrays(self) -> None: ...
    def memory_map_arrays(self) -> None: ...
    def save(self, output_path: Path) -> None: ...
    @classmethod
    def load(cls, output_path: Path) -> SingleRecordingRuntimeData: ...

@dataclass
class CombinedData:
    detection: DetectionData
    extraction: ExtractionData
    plane_count: int = ...
    combined_height: int = ...
    combined_width: int = ...
    tau: float = ...
    sampling_rate: float = ...
    plane_heights: NDArray[np.uint16] = field(default_factory=Incomplete)
    plane_widths: NDArray[np.uint16] = field(default_factory=Incomplete)
    plane_y_offsets: NDArray[np.int32] = field(default_factory=Incomplete)
    plane_x_offsets: NDArray[np.int32] = field(default_factory=Incomplete)
    registered_binary_paths: tuple[Path, ...] = ...
    registered_binary_paths_channel_2: tuple[Path, ...] | None = ...
    def save(self, root_path: Path) -> None: ...
    @classmethod
    def load(cls, root_path: Path) -> CombinedData: ...
    @classmethod
    def _load_metadata(cls, root_path: Path) -> dict: ...

def _save_optional_array_field(
    field_name: str,
    arrays: list[NDArray[np.float32] | NDArray[np.int32] | NDArray[np.bool_] | tuple[int, ...] | None],
    save_dictionary: dict[str, NDArray[np.float32] | NDArray[np.int32] | NDArray[np.bool_] | NDArray[np.uint32]],
    dtype: type,
) -> None: ...
def _load_optional_array_field(
    field_name: str, item_count: int, data: NpzFile, dtype: type
) -> list[NDArray[np.float32] | NDArray[np.int32] | NDArray[np.bool_] | None]: ...
