from typing import Literal

from ..io import resolve_recording_roots as resolve_recording_roots
from ..dataclasses import (
    MultiRecordingConfiguration as MultiRecordingConfiguration,
    SingleRecordingConfiguration as SingleRecordingConfiguration,
)
from .mcp_instance import mcp as mcp

_MAX_SPEED_FACTOR: int
_MAX_PERCENTAGE: int
_FORBIDDEN_FILESYSTEM_CHARACTERS: frozenset[str]
_MAXIMUM_CONTROL_CHARACTER_ORDINAL: int

def generate_config_file(
    output_path: str, pipeline_type: Literal["single-recording", "multi-recording"]
) -> dict[str, str | bool]: ...
def discover_recordings_tool(root_directory: str) -> dict[str, object]: ...
def resolve_dataset_name_tool(
    dataset_name: str, recording_paths: list[str], specifier: str = ""
) -> dict[str, object]: ...
def read_config_file(file_path: str) -> dict[str, str | bool | list[str] | dict[str, object] | None]: ...
def validate_config_file(file_path: str) -> dict[str, str | bool | list[str] | dict[str, dict[str, object]]]: ...
def _to_json_compatible(value: object) -> object: ...
def _identify_non_default_parameters(
    config: object, default: object, prefix: str = ""
) -> dict[str, dict[str, object]]: ...
def _validate_single_recording(config: SingleRecordingConfiguration) -> tuple[list[str], list[str]]: ...
def _validate_multi_recording(config: MultiRecordingConfiguration) -> tuple[list[str], list[str]]: ...
def _validate_filesystem_name(name: str, field_label: str) -> str | None: ...
