from typing import Literal
from pathlib import Path

from ..io import resolve_recording_roots as resolve_recording_roots
from ..layout import (
    PARAMETERS_FILENAME as PARAMETERS_FILENAME,
    OUTPUT_DIRECTORY_NAME as OUTPUT_DIRECTORY_NAME,
    COMBINED_METADATA_FILENAME as COMBINED_METADATA_FILENAME,
)
from ..dataclasses import (
    BaselineMethod as BaselineMethod,
    ReferenceImageType as ReferenceImageType,
    RegistrationBackend as RegistrationBackend,
    MultiRecordingConfiguration as MultiRecordingConfiguration,
    SingleRecordingConfiguration as SingleRecordingConfiguration,
)
from .mcp_instance import mcp as mcp

_MAXIMUM_SPEED_FACTOR: int
_MAXIMUM_PERCENTAGE: int
_FORBIDDEN_FILESYSTEM_CHARACTERS: frozenset[str]
_MAXIMUM_CONTROL_CHARACTER_ORDINAL: int

def generate_config_file_tool(
    output_path: str, pipeline_type: Literal["single-recording", "multi-recording"]
) -> dict[str, str | bool]: ...
def discover_recordings_tool(root_directory: str) -> dict[str, object]: ...
def resolve_dataset_name_tool(dataset_name: str, output_roots: list[str], specifier: str = "") -> dict[str, object]: ...
def read_config_file_tool(file_path: str) -> dict[str, str | bool | list[str] | dict[str, object] | None]: ...
def validate_config_file_tool(file_path: str) -> dict[str, str | bool | list[str] | dict[str, dict[str, object]]]: ...
def set_config_values_tool(file_path: str, values: dict[str, object]) -> dict[str, object]: ...
def _discover_marker_parents(root_path: Path, marker_name: str) -> list[Path]: ...
def _pair_marker_parents_with_roots(marker_parents: list[Path]) -> list[tuple[Path, Path]]: ...
def _resolve_marker_output_root(recording_root: Path, marker_parent: Path) -> Path: ...
def _convert_to_json_compatible(value: object) -> object: ...
def _identify_non_default_parameters(
    config: object, default: object, prefix: str = ""
) -> dict[str, dict[str, object]]: ...
def _validate_single_recording(config: SingleRecordingConfiguration) -> tuple[list[str], list[str]]: ...
def _validate_multi_recording(config: MultiRecordingConfiguration) -> tuple[list[str], list[str]]: ...
def _validate_filesystem_name(name: str, field_label: str, action: str = "resolve dataset name") -> str | None: ...
def _resolve_parameter_assignment(
    configuration: object, dotted_path: str, value: object
) -> tuple[object, str, object] | str: ...
def _resolve_writable_fields(instance: object) -> dict[str, object]: ...
def _coerce_parameter_value(value: object, annotation: object) -> tuple[object, bool]: ...
def _coerce_tuple_value(value: object, annotation: object) -> tuple[object, bool]: ...
def _describe_annotation(annotation: object) -> str: ...
