from typing import ClassVar
from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray as NDArray

from ..dataclasses import (
    ROIMask as ROIMask,
    ROIStatistics as ROIStatistics,
)

def estimate_diameter_from_rois(rois: list[ROIMask], default_diameter: int = 10) -> int: ...
def compute_median_pixel_position(y_pixels: NDArray[np.int32], x_pixels: NDArray[np.int32]) -> tuple[int, int]: ...
def compute_roi_statistics(
    rois: list[ROIStatistics],
    frame_height: int,
    frame_width: int,
    aspect: float | None = None,
    diameter: int | None = None,
    maximum_overlap_fraction: float | None = None,
    crop: bool = True,
    lightweight: bool = False,
) -> None: ...

@dataclass(frozen=True)
class _EllipseData:
    centroid: NDArray[np.float32]
    covariance: NDArray[np.float32]
    radii: tuple[float, float]
    boundary_points: NDArray[np.float32]
    y_scale: int
    x_scale: int
    @property
    def area(self) -> float: ...
    @property
    def radius(self) -> float: ...
    @property
    def aspect_ratio(self) -> float: ...

def _compute_distance_kernel(radius: int) -> NDArray[np.float32]: ...

class _ROI:
    _baseline_cache: ClassVar[dict[int, NDArray[np.float32]]]
    _data: ROIStatistics
    _diameter: int
    _crop: bool
    _cached_soma_mask: NDArray[np.bool_] | None
    def __init__(self, data: ROIStatistics, diameter: int, crop: bool = True) -> None: ...
    @property
    def data(self) -> ROIStatistics: ...
    @property
    def y_pixels(self) -> NDArray[np.int32]: ...
    @property
    def x_pixels(self) -> NDArray[np.int32]: ...
    @property
    def pixel_weights(self) -> NDArray[np.float32]: ...
    @property
    def centroid(self) -> tuple[int, int]: ...
    @property
    def soma_mask(self) -> NDArray[np.bool_]: ...
    @property
    def mean_radius(self) -> float: ...
    @property
    def baseline_mean_radius(self) -> float: ...
    @property
    def compactness(self) -> float: ...
    @property
    def solidity(self) -> float: ...
    @property
    def soma_pixel_count(self) -> int: ...
    @property
    def pixel_count(self) -> int: ...
    def _compute_soma_mask(self) -> NDArray[np.bool_]: ...
    def fit_ellipse(self, y_scale: int, x_scale: int) -> _EllipseData: ...
    def get_overlap_mask(self, overlap_count_image: NDArray[np.uint16]) -> NDArray[np.bool_]: ...
    @staticmethod
    def get_overlap_count_image(rois: list[_ROI], height: int, width: int) -> NDArray[np.uint16]: ...
    @staticmethod
    def remove_overlapping_rois(
        rois: list[_ROI], overlap_image: NDArray[np.uint16], maximum_overlap_fraction: float
    ) -> list[bool]: ...
