import numpy as np
from numpy.typing import NDArray as NDArray

_MINIMUM_STANDARD_DEVIATION: float
_GAUSSIAN_KERNEL_THRESHOLD: int

def apply_temporal_high_pass_filter(frames: NDArray[np.float32], kernel_size: int) -> None: ...
def compute_temporal_standard_deviation(frames: NDArray[np.float32]) -> NDArray[np.float32]: ...
def downsample(data: NDArray[np.float32], taper_edge: bool = True) -> NDArray[np.float32]: ...
def compute_thresholded_variance(frames: NDArray[np.float32], intensity_threshold: float) -> NDArray[np.float32]: ...
def compute_spatial_taper_mask(sigma: float, height: int, width: int) -> NDArray[np.float32]: ...
def compute_block_smoothing_kernel(x_block_count: int, y_block_count: int) -> NDArray[np.float32]: ...
def compute_registration_blocks(
    height: int, width: int, block_size: tuple[int, int] = (128, 128)
) -> tuple[list[NDArray[np.int32]], list[NDArray[np.int32]], tuple[int, int], tuple[int, int], NDArray[np.float32]]: ...
def _apply_gaussian_high_pass(frames: NDArray[np.float32], kernel_size: int) -> None: ...
def _apply_rolling_mean_high_pass(frames: NDArray[np.float32], kernel_size: int) -> None: ...
def mean_centered_meshgrid(height: int, width: int) -> tuple[NDArray[np.float32], NDArray[np.float32]]: ...
