import numpy as np
from numpy.typing import NDArray as NDArray

def compute_bidirectional_phase_offset(frames: NDArray[np.float32]) -> int: ...
def apply_bidirectional_phase_correction(frames: NDArray[np.float32], bidirectional_phase_offset: int) -> None: ...
