from collections.abc import Iterator

import numpy as np
from numpy.typing import NDArray as NDArray

from .spline_grid import (
    SplineGrid as SplineGrid,
    compute_cardinal_coefficients as compute_cardinal_coefficients,
)

_MINIMUM_DIFFUSION_SIGMA: float
_CUBIC_INTERPOLATION_ORDER: int
_BILINEAR_INTERPOLATION_ORDER: int
_BOUNDARY_TOLERANCE: float

def diffuse(data: NDArray[np.float32], sigma: float | list[float]) -> NDArray[np.float32]: ...
def zoom(data: NDArray[np.float32], factor: float | tuple[float, float], order: int = 3) -> NDArray[np.float32]: ...

class Deformation:
    _field_shape: tuple[int, int]
    _fields: list[NDArray[np.float32]]
    def __init__(self, field_y: NDArray[np.float32], field_x: NDArray[np.float32]) -> None: ...
    @classmethod
    def identity(cls, height: int, width: int) -> Deformation: ...
    def __repr__(self) -> str: ...
    @property
    def is_identity(self) -> bool: ...
    @property
    def ndim(self) -> int: ...
    @property
    def field_shape(self) -> tuple[int, ...]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> NDArray[np.float32]: ...
    def __iter__(self) -> Iterator[NDArray[np.float32]]: ...
    def __add__(self, other: Deformation) -> Deformation: ...
    def copy(self) -> Deformation: ...
    def scale(self, factor: float) -> Deformation: ...
    def add(self, other: Deformation) -> Deformation: ...
    def compose(self, other: Deformation) -> Deformation: ...
    def resize_field(self, new_height: int, new_width: int) -> Deformation: ...
    def get_field(self, dimension: int) -> NDArray[np.float32]: ...
    def get_deformation_locations(self) -> tuple[NDArray[np.float32], NDArray[np.float32]]: ...
    def apply_deformation(self, data: NDArray[np.float32], interpolation: int = 3) -> NDArray[np.float32]: ...
    def inverse(self) -> Deformation: ...
    def regularize(
        self, grid_sampling: float, injective: bool = True, injective_factor: float = 0.9, freeze_edges: bool = True
    ) -> Deformation | None: ...
    def crop(self, origin: tuple[int, int], crop_size: tuple[int, int]) -> tuple[Deformation, tuple[int, int]]: ...

def _create_diffusion_kernel(sigma: float) -> NDArray[np.float32]: ...
def _make_samples_absolute(
    delta_x: NDArray[np.float32], delta_y: NDArray[np.float32]
) -> tuple[NDArray[np.float32], NDArray[np.float32]]: ...
def _warp(
    data: NDArray[np.float32],
    result: NDArray[np.float32],
    samples_x: NDArray[np.float32],
    samples_y: NDArray[np.float32],
    order: int,
) -> None: ...
def _project(
    data: NDArray[np.float32],
    result: NDArray[np.float32],
    samples_x: NDArray[np.float32],
    samples_y: NDArray[np.float32],
) -> None: ...
def _resize(data: NDArray[np.float32], new_height: int, new_width: int, order: int = 3) -> NDArray[np.float32]: ...
