import numpy as np
from numpy.typing import NDArray as NDArray

_MINIMUM_KNOTS_FOR_FROZEN_EDGES: int

def compute_cardinal_coefficients(interpolation_factor: float, coefficients: NDArray[np.float32]) -> None: ...
def compute_basis_coefficients(interpolation_factor: float, coefficients: NDArray[np.float32]) -> None: ...

class SplineGrid:
    _field_shape: tuple[int, int]
    _grid_sampling: float
    _grid_shape: tuple[int, int]
    _knots: tuple[NDArray[np.float32], NDArray[np.float32]]
    def __init__(self, field_height: int, field_width: int, sampling: float) -> None: ...
    @property
    def ndim(self) -> int: ...
    @property
    def field_shape(self) -> tuple[int, int]: ...
    @property
    def grid_shape(self) -> tuple[int, int]: ...
    @property
    def grid_sampling(self) -> float: ...
    @staticmethod
    def compute_grid_shape(field_height: int, field_width: int, grid_sampling: float) -> tuple[int, int]: ...
    @property
    def deformation_fields(self) -> tuple[NDArray[np.float32], NDArray[np.float32]]: ...
    def set_from_fields(
        self,
        field_y: NDArray[np.float32],
        field_x: NDArray[np.float32],
        injective: bool = True,
        injective_factor: float = 0.9,
        freeze_edges: bool = True,
    ) -> bool: ...
    def _get_knots(self, dimension: int) -> NDArray[np.float32]: ...
    def _unfold(self, factor: float = 0.9) -> None: ...
    def _freeze_edges(self) -> bool: ...

def _sample_grid(result: NDArray[np.float32], grid_sampling: float, knots: NDArray[np.float32]) -> None: ...
def _fit_knots_to_field(grid_sampling: float, knots: NDArray[np.float32], field: NDArray[np.float32]) -> None: ...
