import numpy as np
from numpy.typing import NDArray as NDArray

from ..detection import mean_centered_meshgrid as mean_centered_meshgrid

NORMALIZATION_EPSILON: float

def apply_phase_correlation(
    frames: NDArray[np.float32], kernel: NDArray[np.complex64], workers: int
) -> NDArray[np.float32]: ...
def apply_mask(
    frames: NDArray[np.float32], mask: NDArray[np.float32], offset: NDArray[np.float32]
) -> NDArray[np.float32]: ...
def combine_rigid_offsets(
    offset_list: list[tuple[NDArray[np.int32], NDArray[np.int32], NDArray[np.float32]]],
) -> tuple[NDArray[np.int32], NDArray[np.int32], NDArray[np.float32]]: ...
def combine_nonrigid_offsets(
    offset_list: list[tuple[NDArray[np.float32], NDArray[np.float32], NDArray[np.float32]]],
) -> tuple[NDArray[np.float32], NDArray[np.float32], NDArray[np.float32]]: ...
def compute_gaussian_frequency_filter(sigma: float, height: int, width: int) -> NDArray[np.complex64]: ...
def apply_temporal_smoothing(frames: NDArray[np.float32], sigma: float) -> NDArray[np.float32]: ...
def apply_spatial_smoothing(data: NDArray[np.float32], window: int) -> NDArray[np.float32]: ...
def apply_spatial_high_pass(data: NDArray[np.float32], window: int) -> NDArray[np.float32]: ...
def compute_reference_fft(reference_image: NDArray[np.float32]) -> NDArray[np.complex64]: ...
def compute_upsampling_kernel(padding: int, subpixel: int = 10) -> tuple[NDArray[np.float32], int]: ...
def _compute_gaussian_rbf_weights(
    source_coordinates: NDArray[np.float64], target_coordinates: NDArray[np.float64], sigma: float = 0.85
) -> NDArray[np.float64]: ...
def _get_normalization_weights(height: int, width: int, window: int) -> NDArray[np.float32]: ...
