"""This module contains the high-level API for the multi-day suite2p processing pipeline."""

import os
from typing import Any
from pathlib import Path

from tqdm import tqdm
import numpy as np
from natsort import natsorted
from ataraxis_time import PrecisionTimer
from ataraxis_base_utilities import LogLevel, console, ensure_directory_exists

from .version import version, sl_version, python_version
from .multiday import (
    import_sessions,
    register_sessions,
    extract_session_traces,
    export_masks_and_images,
    generate_template_masks,
    backward_transform_masks,
    extract_unique_components,
)
from .configuration import MultiDayS2PConfiguration, generate_default_multiday_ops

# THe minimum number of sessions required for multi-day processing
_MINIMUM_SESSION_COUNT = 2


def _find_combined_path(input_directory: Path) -> Path:
    """Finds and validates the 'combined' folder path within a session directory.

    Args:
        input_directory: The path to the directory that stores the single-day suite2p data for the processed session.

    Returns:
        The path to the 'combined' single-day pipeline folder of the processed session.

    Raises:
        RuntimeError: If the expected 'combined' folder is not found or multiple are found.
    """
    combined_path_list = list(input_directory.rglob("combined"))
    if len(combined_path_list) != 1:
        message = (
            f"Unable to run the multi-day processing pipeline. Expected each path provided under the "
            f"'session_directories' multi-day configuration file field to point to a directory tree with exactly one "
            f"'combined' folder. Instead, encountered at least one path pointing to a directory tree with "
            f"{len(combined_path_list)} 'combined' folders."
        )
        console.error(message=message, error=RuntimeError)
        raise RuntimeError(message)  # Fallback to appease mypy, should not be reachable

    return combined_path_list.pop()


def resolve_multiday_ops(ops: dict[str, Any], db: dict[str, Any]) -> Path:
    """Generates the output directory hierarchy and the multiday 'ops.npy' file for the multi-day suite2p pipeline,
    using the configuration parameters from ops and db.

    This function should be used before the first step (multi-day registration) of the multi-day suite2p pipeline to
    generate the necessary directories and files used by the further pipeline steps. During step-wise pipeline
    execution, this function can also be used between steps to update the 'ops.npy' file with new runtime parameters.

    Notes:
        All multi-day pipeline functions require the path generated by this function as the 'ops_path' argument.

        Since the multi-day pipeline uses the outputs of the single-day pipeline, this function merges the multi-day
        configuration parameters into the single-day configuration file of each processed session. Both 'ops' and 'db'
        can contain single-day and multi-day parameters to override them as necessary to support runtime.

        If both 'ops' and 'db' do not contain some of the expected multiday parameters, they are set using
        the 'default' dictionary generated using the MultiDayS2PConfiguration.

        Output structure:
        - Each session gets a multiday folder at: {session_suite2p_parent}/multiday/{dataset_name}/
        - The dataset directory (separate from sessions) stores the tracker file and shared config copies.

    Args:
        ops: A dictionary that contains the multi-day configuration parameters.
        db: An optional dictionary that contains the same keys as 'ops'. Values from this dictionary are used to
            override the matching keys in the 'ops' dictionary.

    Returns:
        The path to the generated 'ops.npy' file in the dataset directory.
    """
    # Since this step takes a noticeable amount of time, notifies the user about the progress of this step.
    console.echo(f"Resolving the multi-day 'ops' dictionary for {len(ops['session_directories'])} sessions...")

    # Builds up the multiday 'ops' dictionary. First fills the dictionary with the 'default' keys. Then
    # overwrites all default keys with keys from the input 'ops' dictionary. Finally, overwrites any keys from the
    # input 'db' dictionary with values from 'db'. This way, there is the following order of precedence:
    # db > ops > default.
    ops = {
        **generate_default_multiday_ops(as_dict=True),
        **ops,
        **db,
        # Actualizes version information
        "base_suite2p_version": version,
        "sl_suite2p_version": sl_version,
        "python_version": python_version,
    }

    # If the user does not specify the maximum parallel worker limit, sets it based on the number of available
    # CPU cores
    if ops["parallel_workers"] < 1:
        # noinspection PyUnresolvedReferences
        ops["parallel_workers"] = os.process_cpu_count()

    # Ensures that the resolved 'ops' file contains at least two sessions to process.
    if len(ops["session_directories"]) < _MINIMUM_SESSION_COUNT:
        message = (
            f"Unable to run multi-day processing using the input parameters. Specifically, expected at least two "
            f"items provided under the 'session_directories' configuration file field, but instead encountered "
            f"{len(ops['session_directories'])}."
        )
        console.error(message=message, error=RuntimeError)

    # Extracts dataset configuration
    dataset_name = ops["dataset_name"]
    dataset_directory = Path(ops["dataset_directory_path"])
    ensure_directory_exists(dataset_directory)

    # Builds a list of unique path components for each session. Assuming all sessions use unique names, this generates
    # a list of unique session IDs from their paths.
    sessions = natsorted([Path(session) for session in ops["session_directories"]])
    ops["session_ids"] = extract_unique_components(paths=sessions)

    # Extracts the paths to the processed session directories.
    session_directories = ops["session_directories"]

    # Processes each session and creates multiday output folders under each session's directory.
    multiday_output_paths: list[str] = []
    last_combined_path = Path()

    with tqdm(
        total=len(session_directories), desc="Processing sessions", disable=not ops["progress_bars"], unit="session"
    ) as pbar:
        for directory in session_directories:
            # Finds the 'combined' folder to locate the suite2p output directory.
            combined_path = _find_combined_path(Path(directory))
            last_combined_path = combined_path

            # The suite2p folder is the parent of 'combined'. Creates 'multiday' at the same level as suite2p.
            suite2p_parent = combined_path.parent.parent  # Goes from combined -> suite2p -> parent

            # Creates multiday output folder for this session: {suite2p_parent}/multiday/{dataset_name}/
            multiday_output = suite2p_parent.joinpath("multiday", dataset_name)
            ensure_directory_exists(multiday_output)
            multiday_output_paths.append(str(multiday_output))

            pbar.update(1)

    # Stores multiday output paths in ops for use by other pipeline functions.
    ops["multiday_output_paths"] = multiday_output_paths

    # Resolves the path to the 'combined' folder ops.npy file for the last session processed by the loop above. This
    # file contains all single-day processing parameters, some of which are reused at the end of the multi-day pipeline
    # (during fluorescence extraction). Then, loads the combined ops into memory as a dictionary. Note, this approach
    # EXPECTS all sessions to share the same single-day parameters and many of the descriptive characteristics (such as
    # imaging fields) to work as expected.
    ops_combined: dict[str, Any] = np.load(last_combined_path.joinpath("ops.npy"), allow_pickle=True).item()

    # Merges the multi-day runtime parameters into the single-day ops dictionary. This generates a
    # combined config that holds both the single-day and the multi-day processing parameters. Also, since 'ops'
    # overrides single-day 'ops_combined', users can overwrite the parameters inside the single-day 'ops' dictionary
    # as necessary to support their runtime.
    multiday_ops = {
        **ops_combined,
        **ops,
        "allow_overlap": True,  # Required for multi-day signal extraction to work as expected
    }

    # Generates the multi-day configuration object for YAML export.
    multi_day_config = MultiDayS2PConfiguration.from_ops(ops_dict=ops)

    # Saves ops.npy and configuration to each session's multiday folder.
    for multiday_output in multiday_output_paths:
        output_path = Path(multiday_output)
        np.save(output_path.joinpath("ops.npy"), multiday_ops, allow_pickle=True)
        multi_day_config.to_config(file_path=output_path.joinpath("multi_day_ss2p_configuration.yaml"))

    # Also saves to the dataset directory for reference and tracker location.
    np.save(dataset_directory.joinpath("ops.npy"), multiday_ops, allow_pickle=True)
    multi_day_config.to_config(file_path=dataset_directory.joinpath("multi_day_ss2p_configuration.yaml"))

    # Returns the path to the ops.npy file in the dataset directory.
    return dataset_directory.joinpath("ops.npy")


def run_s2p_multiday(ops_path: Path) -> None:
    """Executes the multi-day suite2p processing pipeline using the parameters stored in the target ops.npy file.

    This function sequentially calls all steps of the suite2p multi-day processing pipeline, extracting cell
    fluorescence data from cells tracked across multiple sessions (days) pre-processed with the single-day suite2p
    pipeline.

    Notes:
        This function works as a high-level API wrapper over the two pipeline step functions: 'discover_multiday_cells'
        and 'extract_multiday_fluorescence'.

    Args:
         ops_path: The path to the ops.npy file that stores the multi-day suite2p processing parameters. Compatible
            ops.npy files are generated by the resolve_multiday_ops() function.
    """
    # Guards against invalid inputs.
    if not ops_path.exists() or not ops_path.is_file() or ops_path.suffix != ".npy":
        message = (
            f"Unable to run the multi-day suite2p pipeline, as the 'ops.npy' file does not exist at the specified "
            f"path {ops_path}."
        )
        console.error(message=message, error=FileNotFoundError)

    # Instantiates and resets the execution timer
    timer = PrecisionTimer("s")
    timer.reset()

    console.echo(message="Initializing multi-day suite2p runtime...", level=LogLevel.INFO)

    # Loads the configuration data into memory
    ops = np.load(ops_path, allow_pickle=True).item()

    # Step 1: Tracks cells active across processed sessions and generates the ROI masks for the tracked cells in the
    # visual space of each processed session.
    discover_multiday_cells(ops_path)

    # Step 2: Extracts the across-day-tracked cell fluorescence for each processed session.
    for session in ops["session_ids"]:
        extract_multiday_fluorescence(ops_path, session)

    message = f"Multi-day suite2p runtime: Complete. Total time: {timer.elapsed} seconds."
    console.echo(message=message, level=LogLevel.SUCCESS)


def discover_multiday_cells(ops_path: Path) -> None:
    """Discovers reliably identifiable cells and tracks them across the processed set of sessions.

    Notes:
        As part of its runtime, this function fills the output folder for each session with the results of
        across-day cell tracking, including the masks used by the second pipeline step.

    Args:
        ops_path: The path to the ops.npy file that stores multi-day suite2p processing parameters. Compatible ops.npy
            files are generated by the resolve_multiday_ops() function.
    """
    # Verifies the input ops.npy file.
    if not ops_path.exists() or not ops_path.is_file() or ops_path.suffix != ".npy":
        message = (
            f"Unable to run the multi-day suite2p pipeline, as the 'ops.npy' file does not exist at the specified "
            f"path {ops_path}."
        )
        console.error(message=message, error=FileNotFoundError)
    ops = np.load(ops_path, allow_pickle=True).item()

    # Initializes the runtime timer
    timer = PrecisionTimer("s")
    step_timer = PrecisionTimer("s")  # Times the whole registration processing step.
    step_timer.reset()

    # Imports the data required to carry out registration for each session.
    console.echo(message="Importing requested session data for multi-day registration...")
    timer.reset()
    sessions_data = import_sessions(ops=ops)
    console.echo(message=f"Session data: imported. Time taken: {timer.elapsed} seconds.", level=LogLevel.SUCCESS)

    # Registers all sessions across days (to the same deformed visual field) by generating and applying the deformation
    # offsets to all reference images and cell masks of every session.
    console.echo(message="Registering sessions across days...")
    timer.reset()
    sessions_data = register_sessions(ops=ops, data=sessions_data)
    console.echo(message=f"Registration: complete. Time: {timer.elapsed}s.", level=LogLevel.SUCCESS)

    # Tracks cells across sessions in the deformed visual space and computes the template masks for cells that can be
    # identified across sessions to apply to the original visual space of each session
    console.echo(message="Computing across-session cell masks...")
    timer.reset()
    sessions_data = generate_template_masks(ops=ops, data=sessions_data)
    console.echo(message=f"Across-session cell masks: computed. Time: {timer.elapsed}s.", level=LogLevel.SUCCESS)

    # Transforms the template cell masks from the shared multi-session (deformed) visual space to the original
    # (unregistered) visual space of each session. This is necessary to re-extract the fluorescence of multi-day-tracked
    # cells from each session during the second step of the multi-day pipeline.
    console.echo(message="Transforming template cell masks from multi-day visual space to single-day visual space...")
    timer.reset()
    sessions_data = backward_transform_masks(ops=ops, data=sessions_data)
    console.echo(message=f"Cell masks: transformed. Time: {timer.elapsed}s.", level=LogLevel.SUCCESS)

    # Exports all data generate during the first (registration) step to disk. The data is then reloaded as part of the
    # second (extraction) step.
    console.echo(message="Appending multi-day registration data to each session's suite2p (output) folder...")
    export_masks_and_images(ops=ops, data=sessions_data)
    console.echo(message=f"Multi-day registration: complete. Time: {step_timer.elapsed}s.", level=LogLevel.SUCCESS)


def extract_multiday_fluorescence(ops_path: Path, session_id: str) -> None:
    """Extracts the fluorescence data from cells tracked across the processed set of sessions.

    Args:
        ops_path: The path to the ops.npy file that stores multi-day suite2p processing parameters. Compatible ops.npy
            files are generated by the resolve_multiday_ops() function.
        session_id: The unique ID of the session for which to extract the across-day-tracked cell fluorescence. The ID
            has to match one of the unique session IDs stored under the 'session_ids' field of the dictionary loaded
            from the ops.npy file.
    """
    # Verifies the input ops.npy file.
    if not ops_path.exists() or not ops_path.is_file() or ops_path.suffix != ".npy":
        message = (
            f"Unable to run the multi-day suite2p pipeline, as the 'ops.npy' file does not exist at the specified "
            f"path {ops_path}."
        )
        console.error(message=message, error=FileNotFoundError)

    ops = np.load(ops_path, allow_pickle=True).item()

    # Gets session IDs and multiday output paths from ops.
    session_ids: list[str] = ops["session_ids"]
    multiday_output_paths: list[str] = ops["multiday_output_paths"]

    if session_id not in session_ids:
        message = (
            f"Unable to extract across-day-tracked cell activity data for session '{session_id}' as this ID is not "
            f"inside the session_ids list loaded from the ops.npy file specified by the {ops_path} path."
        )
        console.error(message=message, error=ValueError)

    # Uses the session ID to find the corresponding multiday output path and derive the suite2p folder.
    session_index = session_ids.index(session_id)
    multiday_output = Path(multiday_output_paths[session_index])

    # The suite2p folder is at the same level as the 'multiday' folder.
    # multiday_output is: {suite2p_parent}/multiday/{dataset_name}/
    # We need: {suite2p_parent}/suite2p/
    suite2p_parent = multiday_output.parent.parent
    target_session_folder = suite2p_parent.joinpath("suite2p")

    # Calls the trace extraction function.
    extract_session_traces(ops=ops, session_folder=target_session_folder, session_id=session_id)
