"""This module statically resolves and stores the Python and library version information. This information is added to
each 'ops.npy' file generated by both single-day and multi-day pipelines to support runtime reproducibility.
"""

import sys

from importlib_metadata import metadata as _metadata

version = _metadata("sl-suite2p")["version"]
python_version = f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
